server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://192.168.63.130:3306/myblog?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.63.130
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 0
    password: 123321

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.blog.pojo
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL到控制台

logging:
  level:
    org.mybatis: debug  # 设置 MyBatis 的日志级别为 debug，查看 SQL 日志
    com:
      sky:
        mapper: debug
        service: info
        controller: info
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tMMgy9xCofRSMUD3iDS
    accessKeySecret: Fe3cMOgbj7IXVfiyleMXg5hzu6Lz6U
    bucketName: web-tlias-tencent